name: "Pip"
# Test pip install after OpenSim setup

on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches:
  #     - master
  #     - main

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.12"]
        #python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup dependencies and OpenSim
      run: make setup

    - name: Build and install with pip
      run: pip install --verbose .[test]

    - name: Run tests
      run: make test